<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot" Version="5.0.55" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Refinement\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="NNs\Lstm\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="NNs\Lstm\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="NNs\Lstm\**" />
  </ItemGroup>

</Project>
