<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Opal\Opal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BinTest.cs" />
    <Compile Remove="CatalogTests.cs" />
    <Compile Remove="DiagnosticTest.cs" />
    <Compile Remove="FfTests.cs" />
    <Compile Remove="GpuTest.cs" />
    <Compile Remove="LstmTests.cs" />
    <Compile Remove="Program.cs" />
    <Compile Remove="RecurrentTests.cs" />
    <Compile Remove="ScalarMultiplyDiagnosticTest.cs" />
  </ItemGroup>

</Project>
