<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>0.0.0-alpha</Version>
        <Title>Opal.Light</Title>
        <Authors>Jewels</Authors>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
