<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.0.2-alpha</Version>
    <Title>Opal</Title>
    <PackageProjectUrl>https://github.com/jewels86/Opal</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jewels86/Opal.git</RepositoryUrl>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="ILGPU.Algorithms" Version="1.5.3" />
    <PackageReference Include="Jewels.Lazulite" Version="1.7.5-alpha" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Modules\**" />
    <Compile Remove="NNs\Ff\ScalarFfNetwork.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Modules\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Modules\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
</Project>
